---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: server
    image: "leandelivery/docker-systemd:ubuntu-18.04"
    privileged: yes
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    networks:
      - name: test-sshd-role
  - name: client
    image: "debian:10"
    networks:
      - name: test-sshd-role
provisioner:
  name: ansible
  lint:
    name: ansible-lint
verifier:
  name: ansible
  lint:
    name: ansible-lint
