---
- name: verify
  hosts: client
  tasks:
    - name: perform SSH connection to server
      expect:
        command: ssh root@server
        responses: {
          "yes/no": "yes",
          "password": "root-password"
        }
        timeout: 5
      changed_when: false
      register: result

    - name: check that command prompt has appeared
      assert:
        that: "'root@server:~#' in result.stdout_lines[-1]"
